import Head from 'next/head';

import Header from '../src/components/global/Header/Header';

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <div>welcome</div>
      </Head>
      <Header />
    </div>
  );
}

export default Home;
