import { Container } from '@mui/material';
import Head from 'next/head';

import TransferForm from '../src/components/pages/Home/TransferForm/TransferForm';

function Home() {
  const onSubmit = (values) => {
    console.info('values', values);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <div>welcome</div>
      </Head>
      <Container>
        <TransferForm onSubmit={onSubmit} />
      </Container>
    </div>
  );
}

export default Home;
